import * as React from 'react';

class Terms extends React.Component<any, any> {
  render() {
    return (
      <div className="Terms">
        <div className="container">
        <h2>Terms and Conditions</h2>
        <h3>INTRODUCTION</h3>
        <ul><li>Simply Put: Spotter/SPOTTER (collectively, “We" "Us" or “Application” or “App”) is a location based social network. Currently providing Free Service. User (alternatively known as “You”, “Your” and “Yourself”) can share photos, videos, text, links, Spotticons (photos of special Emoji’s) and audio that are tied to a location through SpottCards. These SpottCards can be shared with FRIENDS, who are also subscriber of Spotter and have User's contact number. User can view SpottCards of friends, like the Spottcards by Buzzing them. User can also create a TRAIL. Trail is a journey taken by the User from one geographic point to another. Several Users can join in the trail. Users can create SpottCards on the trail signifying their journey together. MAPVIEW of the trail shows the start location, end location as well as all the SpottCards shared by the User and trail friends on the map. NEARBY shows SpottCards of friends which have been shared in the nearby locality. SpottFeed shows all the latest updates of the friends of the User. PRIVACY Settings has two options. On and Off. Keeping the Privacy OFF keeps your location, SpottCards and trails visible to your Friends. Privacy ON hides your location, list of friends and email id. However, friends are able to see profile information , Trails and SpottCards.</li>
        <li>Spotter subject to these terms and conditions (hereinafter referred to as Terms) including those set forth but not restricted to the Spotter Privacy Policy. By accessing, using or downloading any materials from the Application, you agree to follow and agree by the Terms, which may be updated by Spotter from time to time without notice to you. You can review the most current version of the Terms at any time. Spotter and its third party providers may make improvements and/or changes in the products, services, mobile applications, features, programs, and prices described in this Application at any time without notice. Certain provisions of the Terms may be supplemented or superseded by expressly designated legal notices or terms located on particular pages at this Application. The Application is not intended for and is not designed to attract children under age of 18 unless children between the age group of 16 years and 18 years enrol under parental/ legal guidance. If you do not agree with the Terms, please do not use this Application. BY CONTINUING TO BROWSE THESE TERMS, YOU ARE INDICATING YOUR AGREEMENT TO THE TERMS AND ALL REVISIONS THEREOF. We appreciate responsible usage of the service and hope you enjoy it!!</li></ul>
        
        <h3>REGISTRATION</h3>
        <ul><li>To use the services available on the Application, you must complete and agree to:(a) provide true, accurate, current and complete information about yourself as prompted by the Application Sign Up Form and (b) maintain and promptly update Your Application to keep it accurate and current.</li></ul>
        
        <p>Note: You may subscribe by a Pseudonym. Otherwise all the details must be true and accurate.</p>
        
        <ul><li>You agree that Spotter may use your provided information to identify and reflect your information for the first time and then poll every hour or when location changes substantially to track Your location and keep it updated.</li>
        <li>Content provided by You is the sole responsibility of the entity that makes it available. We may review content to determine whether it is illegal or violates our policies, and we may remove or refuse to display content that we reasonably believe violates our policies or the law. But that does not necessarily mean that we review all the contents so updated on the Application by the User.</li>
        <li>Spotter reserves the right to terminate your account, refuse any information and restrict all current or future use of the Application, if it is of the opinion that information updated by You is inaccurate or suspicious. In consideration of your use of the application, you represent that you are to form a binding contract and are not a person barred from receiving services under the laws of any applicable jurisdiction.</li></ul>
        
        <h3>USING Spotter SERVICES</h3>
        <ul><li>Unless otherwise stated, the services featured on this Application are available in various countries across the World. You are solely responsible for evaluating the details mentioned herein and also in other Policy/ies relating to the use of this Application. Redistribution or republication of any part of this Application or its content is prohibited, including such by framing or other similar or any other means, without the express written consent of Spotter.</li>
        <li>You acknowledge and agree that you will have to provide Spotter with your mobile phone number. You expressly acknowledge and agree that in order to provide the Service, Spotter may periodically access your contact list and/or address book on your mobile device to find and keep track of mobile phone numbers of other users of the Service. When providing your mobile phone number, you must provide accurate and complete information. You hereby give your express consent to Spotter to access your contact list and/or address book for mobile phone numbers in order to provide and use the Service.</li>
        <li>You are solely responsible for the status messages and SpottCards that you submit and that are displayed for your mobile phone number on the Spotter Service. You must notify Spotter immediately of any breach of security or unauthorized use of your mobile phone. Although Spotter will not be liable for your losses caused by any unauthorized use of your account, you may be liable for the losses of Spotter or others due to such unauthorized use.</li>
        <li>Don’t misuse our Services. You may use our Services only as permitted by law. We may suspend or stop providing our Services to you if you do not comply with our terms or policies or if we are investigating suspected misconduct.</li>
        <li>In connection with your use of the Services, we may send you service announcements, administrative messages, and other information. Using our Services does not give you ownership of any intellectual property rights in our Services or the content you access. You may not use content from our Services unless you obtain permission from its owner or are otherwise permitted by law. These terms do not grant you the right to use any branding or logos used in our Services. Don’t remove, obscure, or alter any legal notices displayed in or along with our Services.</li>
        <li>We provide our Services using a commercially reasonable level of skill and care and we hope that you will enjoy using them.</li>
        <li>You shall be solely responsible for your own Status Submissions and SpottCards and the consequences of posting or publishing them. Spotter does not represent the views or opinions of its Users and makes no guarantees as to the validity, accuracy or legal status of any status.</li>
        <li>Spotter is under no obligation to monitor any Commercial/ Non Commercial transactions undertaken by you using the Spotter Application. You alone will be responsible for all your conduct under such transactions. You are instructed to satisfy yourself regarding the quality, quantity and fitness of any good and/or service before purchasing/selling the same. Spotter excludes its obligations against any dispute in any such transaction. Such disputes must be solely between You and the other User and/or Third Party. It is clarified that Spotter shall not be responsible or liable for any deficiency in goods and/or services purchased by You using the Spotter Application.</li></ul>
        
        <h3>USER CONDITIONS</h3>
        <ul><li>Age Restrictions. In order to use Spotter you must be 18 of age or older. If you are between 16 and 18 years of age, and you want to use Spotter, please read through the Terms with your parent or legal guardian, and only accept the Terms and use Spotter with the permission of your parent or legal guardian. You must not access Spotter or accept these Terms if you are a person who is either barred or otherwise legally prohibited from receiving or using the Service or any Products under the laws of the country in which you are resident or from which you access or use Spotter.</li>
        <li>Adherence to Laws. As a condition of use, you undertake not to use the Service for any purpose that is prohibited by these Terms of Use and Privacy Policy and any other Rule or regulation so provided from time to time by Spotter. You are responsible for all of your activity in connection with the Service. Additionally, you shall abide by all applicable local, state, national and international laws and regulations and, if you represent a business, any advertising, marketing, privacy, or other self-regulatory code/s applicable to your industry.</li>
        <li>Basic Use Requirements. To use the Service, you will need a Device that meets the system and compatibility requirements for the relevant Product, which may change from time to time, working Internet access, and compatible software. Your ability to use the Service and the performance of the Service may be affected by these factors. Such system requirements are your responsibility.</li>
        <li>Updates: The Spotter may update its Application from time to time; you may need to install the updates to avail uninterrupted services.</li></ul>
        
        <p>One Time Password (OTP): To protect the User on the Internet or through means of telecommunication we generate a One Time Password. This OTP shall be transmitted through the Short Message Service (SMS) by Spotter to Your registered Mobile Number at the time of signing up or through a phone call.</p>
        
        <ul><li>CAUTION: We would like to alert you that any person who is aware of your mobile number and has access to the OTP message we generate at the time of registration, may form an account using his/her mobile device. In order to ensure safety and steer clear of any misuse, we strongly recommend you to keep your OTP discreet and not dispense the OTP to anyone. Spotter holds no liability and should be indemnified if your Spotter account is being used in any other mobile device without your knowledge and consent. User Knowledge: Spotter accepts the mobile number specified by the User at the time of Signing Up. If the User subscribes the application of Spotter from a different mobile device but with the mobile number previously registered with Spotter, to avoid any anomaly the User accepts that in such a case all the actions of the User will be centralised to one User device only which is last signed in.</li>
        <li>Sharing Your Content and Information: You are the sole owner of all the contents and information you post on the Spotter Application. You can control how the SpottCards are visible to others through your privacy and application settings. In addition to the content that is covered by intellectual property rights: Photos and videos (IP content), you specifically grant us a non-exclusive, transferable, sub-licensable, royalty-free, worldwide license to use any IP content that you post on or in connection with Spotter. This IP License ends when you delete your IP content or your account unless your content has been shared with others, and they have not deleted it. You understand and agree that at the time of deleting/terminating your account, removed content may persist in backup copies for a reasonable period of time (but will not be available to others, other than that provided in the Terms.)</li>
        <li>User Consent: In connection with Spottcard submissions, you affirm, represent, and/or warrant that: (i) you own or have the necessary licenses, rights, consents, and permissions to use and authorize Spotter to use all patent, trademark, trade secret, copyright or other proprietary rights in and to any and all Spottcard submissions to enable inclusion and use of the Spottcards in the manner contemplated by the Service and these Terms of Service; and (ii) you have the written consent, release, and/or permission of each and every identifiable individual person in Spottcard submissions to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of the Spottcard submissions in the manner contemplated by the Service and these Terms. To be clear: you retain all of your ownership rights of your Spottcard submissions, but you have to have the rights in the first place.</li>
        <li>User Safety: We do our best to keep Spotter safe, but we cannot guarantee it. We need your help to keep Spotter safe, which includes the following commitments by you:
          <ul><li>You will not collect users' content or information, or otherwise access Spotter, using automated means (such as harvesting bots, robots, spiders, or scrapers) without our prior permission.</li>
          <li>You will not upload viruses or other malicious code. Send or store material containing software viruses, worms, Trojan horses or other harmful computer code, files, scripts, agents or programs.</li>
          <li>In connection with Spottcard submissions, you further agree that you will not: (i) submit material that is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from their rightful owner to post the material and to grant Spotter all of the license rights granted herein; (ii) publish falsehoods or misrepresentations that could damage Spotter or any third party.</li>
          <li>You will not solicit login information or access an account belonging to someone else.</li>
          <li>You will not bully, intimidate, or harass any user.</li>
          <li>You will not post content that: is hate speech, threatening, pornographic; incites violence; nudity or graphic or gratuitous violence or defamatory, libellous, or ethnically offensive, or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise inappropriate.</li>
          <li>You will not use Spotter to do anything unlawful, misleading, malicious, or discriminatory.</li>
          <li>You will not do anything that could disable, overburden, or impair the proper working or appearance of Spotter, such as a denial of service attack or interference with page rendering or other Spotter functionality.</li>
          <li>Interfere with or disrupt the integrity or performance of the Service or the data contained therein; or (viii) attempt to gain unauthorized access to the Service or its related systems or networks.</li>
          <li>You will not facilitate or encourage any violations of this Statement or our policies.</li>
          <li>Do not access another user’s account without their permission.</li>
          <li>Do not create or use multiple accounts to evade our policies or bypass blocks or otherwise subvert restrictions placed on your account. For example, if you’ve been blocked by another user or suspended for abuse, don’t create a replacement account that engages in similar activity</li></ul>
        </li>
        <li>Unauthorised Access to Accounts. You must keep your user details secure and discreet and must not share them with anyone else. You must not collect or harvest any personal data of any user of Spotter in an unauthorised way.</li>
        <li>Deleting Account: The User can delete his/ her account at any point of time owing to his/her discretion. A four (4) digit code is sent to the user for verification on the registered mobile number through Short message Services (SMS), or through a phone call.</li>
        <li>Terminating Accounts. If Spotter disables access to your account, pursuant to these Terms, you may be prevented from accessing Spotter, your account details or any files or other Products that are stored with your account. These will further lead to deletion of your account from Spotter permanently.</li></ul>
        
        <p>Note for (e) and (f): You understand and agree that at the time of deleting/terminating your account; removed content may persist in backup copies for a reasonable period of time (but will not be available to others. However, Spotter reserves every right to disclose any User information if required to Government or any other courts, tribunals, regulatory agencies or law enforcement agencies through laws, applicable in India and other countries where Spotter is accessible.)</p>
        
        <ul><li>Responsibility over conduct: Spotter Service allows users to submit text, photos, videos, audios and other form of communications submitted by you. Any such submissions may be shared, and/or published, and may be visible to other users of the Service who have your mobile phone number and are subscriber of these services. You are responsible for your use of the Services, for any Content you post to the Services, and for any consequences thereof. You should only provide Content that you are comfortable sharing with others under these Terms.. You acknowledge and agree that any Spottcard submissions may be viewed by users that have your mobile phone number.</li>
        <li>Strict clarification: You retain your ownership rights in your Spottcard submission. You understand and agree that Spotter DOES NOT GUARANTEE ANY CONFIDENTIALITY WITH RESPECT TO ANY SUBMISSIONS.</li></ul>
        
        <h3>INTELLECTUAL PROPERTY PROTECTION:</h3>
        <ul><li>You agree and acknowledge that any necessary software used in connection with the Application (if any) and any content available on the Application contain proprietary and confidential information that is protected by applicable intellectual property and other laws. Except as expressly permitted by applicable law or authorized by Spotter or applicable third party service providers or advertisers, you agree not to modify, rent, lease, loan, sell, distribute or create derivative works based on the Application, the software or Content available on the Application (other than Content that you may submit), in whole or in part.</li>
        <li>Spotter grants you a personal, non-transferable and non-exclusive right and license to access and use the Application; provided that you do not (and do not allow any third party to) copy, modify, create a derivative work from, reverse engineer, reverse assemble or otherwise attempt to discover any source code, sell, assign, sublicense, grant a security interest in or otherwise transfer any right in the Application. You agree not to access the application by any means other than through the interface that is provided by Spotter for use in accessing the Application The term Spotter, the Spotter a logo and other Spotter logos and product and service names are the exclusive trademarks of, and are owned by, Spotter, and you may not use or display such trademarks in any manner without Spotter's prior written permission. Any third party trademarks or service marks displayed on the Application are the property of their respective owners. Spotter reserves all rights not expressly granted hereunder.</li></ul>
        
        <h3>DISCLAIMER AND WARRANTIES:</h3>
        <p>OTHER THAN AS EXPRESSLY SET OUT IN THESE TERMS OR ADDITIONAL IN NO EVENT SHALL SPOTTER, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR SERVICE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR SERVERS, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SERVICE BY ANY THIRD PARTY, (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SPOTTER CLIENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT SPOTTER IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND/OR (VI) THE DISCLOSURE OF INFORMATION PURSUANT TO THESE TERMS OF SERVICE OR PRIVACY POLICY. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.</p>
        <p>SOME JURISDICTIONS PROVIDE FOR CERTAIN WARRANTIES, LIKE THE IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, WE EXCLUDE ALL WARRANTIES.</p>

        <h3>LIABILITY FOR OUR SERVICES</h3>
        <p>WHEN PERMITTED BY LAW, SPOTTER, AND SPOTTER’S SUPPLIERS AND DISTRIBUTORS, WILL NOT BE RESPONSIBLE FOR LOST PROFITS, REVENUES, OR DATA, FINANCIAL LOSSES OR INDIRECT, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES.</p>

        <h3>GENERAL CLAUSES:</h3>
        <ul><li>Force Majeure: Neither party shall be liable to the other for any failure to perform any obligation under any Agreement which is due to an event beyond the control of such party including but not limited to any Act of God, terrorism, war, Political insurgence, insurrection, riot, civil unrest, act of civil or military authority, uprising, earthquake, flood or any other natural or manmade eventuality outside of our control, which causes the termination of an agreement or contract entered into, nor which could have been reasonably foreseen. Any Party affected by such event shall forthwith inform the other Party of the same and shall use all reasonable endeavours to comply with the terms and conditions of any Agreement contained herein.</li>
        <li>Warranty and Indemnity: We do not warrant that the service from this Application will be uninterrupted, timely or error free, although it is provided to the best ability. By using this service you thereby indemnify Spotter, its employees, agents and affiliates against any loss or damage, in whatever manner, howsoever caused. Spotter shall also indemnify and keep indemnified the User from and against all loss, damage, or liability suffered by it as a result of the User’s acts or omission. User also agrees to indemnify the Spotter for all claim and demands from third parties as a result of its acts.</li>
        <li>Waiver: Spotter functions as a venue to connect members in a virtual information place. As a neutral facilitator, Spotter is not directly involved in the actual transactions between members of the Application As a result, Spotter has no control over the truth, accuracy, quality, legality, or safety of postings made by users of the Application. Spotter shall have no responsibility to confirm the identity of members. Spotter shall also have no responsibility to confirm or verify the qualifications, background, or abilities of users of the Application. You shall at all time exercise common sense and good judgment when dealing with any user of the Application.</li>
        <li>Severability: If any item or provision contained in this agreement or any part of it is declared or becomes unenforceable, invalid or illegal for any reason whatsoever, including but without detracting from the generality of the foregoing, a decision by the competent court, an Act of Parliament or any statutory or other bye-laws or regulations or any other requirements having the force of law, the other terms/ clauses/ provisions of this Agreement shall remain in full force and effect as if this Agreement had been executed without that term/clause/provision.</li>
        <li>Dispute Resolution Governing Laws And Jurisdiction: Any dispute, controversy or claims arising out of or relating to this Agreement or the breach, termination or invalidity thereof, shall be settled by arbitration in accordance with the provisions of the [Indian] Arbitration and Conciliation Act, 1996.The Arbitral Tribunal shall be composed of one Arbitrator appointed by Spotter. The place of Arbitration shall be at Ahmedabad, Gujarat (INDIA). The Arbitral procedure shall be conducted in English language and the award or awards shall be rendered in English. The procedural law of the Arbitration shall be Indian law. The award of the Arbitral Tribunal shall be final, conclusive and binding upon the Parties, and the provisions of the Arbitration and Conciliation Act, 1996 shall apply. The rights and obligations of the Parties under, or pursuant to, this Clause, including the Arbitration Agreement in this Clause, shall be governed by and be subject to Indian law, and the Agreement shall be subject to the exclusive jurisdiction of the courts at Ahmedabad, Gujarat(INDIA).</li></ul>

        <h3>CONTACT:</h3>
        <p>You may contact Spotter at the following address:</p>
        <address>Techniexe Infolabs LLP<br />
        104, Sumel-II, Near Gurudwara Road,<br />
        S.G Highway, Thaltej, Ahmedabad - 380054 (INDIA)</address>
        <p>Email id: <a href="mailto:info@Spotter.buzz">info@Spotter.buzz</a></p>
        <p>Effective Date: Date 23rd June 2016</p>
      </div>
      </div>
    );
  }
}

export default Terms;
